config/routes.rb
Rails.application.routes.draw do

  root to: 'loans#index'

  devise_for :users
  resources :users do
    resources :loans
  end

  get 'reject', to: 'loans#reject'
  get 'approve', to: 'loans#approve'
  get 'adjustment', to: 'loans#adjustment'
  get 'repay_loan', to: 'loans#repay_loan'


  get 'requested_list', to: 'loans#requested_list'
  get 'approved_list', to: 'loans#approved_list'
  get 'open_list', to: 'loans#open_list'
  get 'reject_list', to: 'loans#reject_list'
  get 'closed_list', to: 'loans#closed_list'


  get 'data_list', to: 'loans#data_list'

  

end

app/models/adjustment.rb
class Adjustment < ApplicationRecord
  belongs_to :loan
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :user
  has_many :adjustments, dependent: :destroy
  has_many :adjustments, class_name: "Loan", foreign_key: "parent_id"
  belongs_to :parent, class_name: "Loan", optional: true

  validates :amount, presence: true
  validates :interest_rate, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  scope :admin, -> { find_by(admin: true) }

  has_many :loans, dependent: :destroy       
  after_create :update_amount

  validates :email, presence: true

  def is_admin?
    self.admin
  end


  private

  def update_amount
    update(amount: 10000) if !self.admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :authenticate_user!
  include LoansHelper

  def index
      if current_user.is_admin?
        @loans = Loan.where(status: requests, parent_id: nil)
      else
        @loans = current_user.loans.where(status: requests, parent_id: nil)
      end
  end

  def show
    if current_user.is_admin?
      @loan = Loan.find_by(id:params[:id])
    else
      @user  = User.find_by(id:params[:user_id])
      @loan = @user.loans.find_by(id:params[:id])
    end
  end
  
  def new
    @user = User.find_by(id: params[:user_id])
    @loan = Loan.new
    respond_to do |format|
      format.js
    end
  end
  
  def create
    @user = User.find_by(id: params[:user_id])
    loan_params[:total_amount]  = loan_params[:amount]
    @loan = @user.loans.new(loan_params)
    if @loan.save
        redirect_to :root    
    else
      render :new, status: :unprocessable_entity
    end
  end

  def reject
    @loans = current_user.loans.where(status: 'rejected')
    @loan = Loan.find_by(id: params[:id])
    @loan.update(status: 'rejected')
    if request.xhr?
      respond_to do |format|
        format.js
      end
    else
      redirect_to root_path
    end
  end

  def approve
    @loans = current_user.loans.where(status: 'approved')
    admin = User.admin
    if params[:loan_id].present?
      if current_user.id != Loan.find_by(id: params[:loan_id]).user_id
        return
      end
      @loan = Loan.find(params[:loan_id])
      final_amount = current_user.amount + @loan.amount
      pending_amount = admin.amount - @loan.amount
      Loan.create(user_id: @loan.user_id,
                  parent_id: @loan.id,
                  interest_rate: @loan.interest_rate,
                  amount: @loan.amount,
                  status: params[:status])  if params[:status] == 'waiting_for_adjustment_acceptance'
      admin.update(amount: pending_amount)
      current_user.update(amount: final_amount)
      @loan.update(status: 'open')
    else
      @user = User.find_by(id: params[:user_id])
      @loan = @user.loans.find_by(id: params[:id])
      @loan.update(status: 'approved')
    end
    if request.xhr?
      respond_to do |format|
        format.js
      end
    else
      redirect_to root_path
    end
  end

  def adjustment
    @loan = Loan.find_by(id: params[:id])
    @user = @loan.user
    respond_to do |format|
      format.js
    end
  end

 def update
    @user = User.find_by(id: params[:user_id])
    @loan = @user.loans.find_by(id: params[:id])
    if current_user.id != @loan.user_id && !current_user.is_admin?
      return
    end
    amount= @loan.amount
    interest_rate= @loan.interest_rate
    status= @loan.status
    loan_params[:status] = 'waiting_for_adjustment_acceptance' if loan_params[:status] != 'readjustment'
    loan_params[:total_amount]  = loan_params[:amount]
    if @loan.update(loan_params)
      @user.loans.create(parent_id: @loan.id, interest_rate: interest_rate, amount: amount, status: status)
      redirect_to root_path
    else
      render :adjustment, status: :unprocessable_entity
    end
  end


  def repay_loan
    @loan = Loan.find_by(id: params[:id])
    user_balance = @loan.user.amount - @loan.total_amount
    admin_balance = User.admin.amount + @loan.total_amount
    @loan.user.update(amount: user_balance)
    User.admin.update(amount: admin_balance)
    @loan.update(status: 'closed')
    @loans = Loan.where(status: requests, parent_id: nil)
    @loans = @loans.where(user_id: current_user.id) unless current_user.is_admin?
    redirect_to root_path
  end


  def data_list
    fetch_loans(status: params[:status])
    respond_to do |format|
      format.js 
    end
  end

  private
  def loan_params
      params.require(:loan).permit!
  end

  def fetch_loans(status: nil)
    status = requests if status == 'requested'
    @loans = Loan.where(status: status, parent_id: nil)
    @loans = @loans.where(user_id: current_user.id) unless current_user.is_admin?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/loans_helper.rb
module LoansHelper

  def requests
    ['requested', 'waiting_for_adjustment_acceptance', 'readjustment']
  end
  
end

app/views/layouts/_navbar.html.erb
  <nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand">Lending Money App 
      <%if current_user.is_admin? %>
        <span style="font-size:12px; margin-left:10px;">Admin</span>
      <% end %>
      </a>
      <form class="d-flex">
        <span class="m-2 text-white p-2"><%= current_user.email %></span>
        <div class="m-2 text-white p-2">Balance: <%= current_user.amount %> Rs</div>
        <% unless current_user.is_admin? %>
          <%= button_tag "Request Loan", id: "my-button", url:'#', type: "button", class: "btn btn-primary m-2", onclick: "requestLoan()" %>
        <% end %>
        <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: "btn btn-danger m-2" %>
      </form>
    </div>
  </nav>
  <script>
    function requestLoan(){
        $.ajax({
            url: '/users/<%= current_user.id %>/loans/new',
            method: 'GET',
            success: function(response) {
                console.log('Success:', response);
            },
            error: function(error) {
                console.log('Error:', error);
            }
        });
    }
  </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LendingMoneyApp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>

  <style>
    body {
      display: flex;
      flex-direction: column;
      height: 100vh;
    }
    .navbar {
      z-index: 1000;
    }
    .main-container {
      display: flex;
      flex: 1;
      overflow: hidden;
    }
    .sidebar {
      min-width: 250px;
      max-width: 250px;
      height: 100%;
      background-color: #343a40;
      /* padding-top: 1rem; */
      overflow-y: auto;
    }
    .sidebar .nav-link {
      color: #fff;
    }
    .sidebar .nav-link.active {
      background-color: #495057;
      color: #fff;
    }
    .content {
      flex: 1;
      padding: 10px;
      overflow-y: auto;
    }
    .sidebar .nav-item:hover {
    background-color: #323b45; /* Change background color on hover */
    color: #fff; /* Change text color on hover */
}
  </style>
</head>

<body>
  <!-- Top Navbar -->
    <%= render "layouts/navbar" if current_user.present? %>

  <!-- Main Container -->
  <div class="main-container">
    <% if current_user.present? %>
      <!-- Sidebar -->
      <div class="sidebar bg-dark">
        <ul class="nav flex-column">
          <li class="nav-item">
            <span class="nav-link active" onclick="getList('requested')">Request</span>
          </li>
          <li class="nav-item">
            <span class="nav-link" onclick="getList('approved')">Approved</span>
          </li>
          <li class="nav-item">
            <span class="nav-link" onclick="getList('open')">Open</span>
          </li>
          <li class="nav-item">
            <span class="nav-link" onclick="getList('rejected')">Rejected</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" onclick="getList('closed')">Closed</a>
          </li>
        </ul>
      </div>
    <% end %>

    <!-- Main Content Area -->
    <div class="content" style="background: #f2f2f2">
      <%= yield %>
    </div>
  </div>
<script>
    function setActiveNavLink(status) {
        $('.nav-link').removeClass('active').addClass('inactive');
        $('.nav-link[onclick*="' + status + '"]').removeClass('inactive').addClass('active');
    }

function getList(status){
    $.ajax({
    url: '/data_list',
    method: 'GET',
    data: { status: status },
    success: function(response) {
        setActiveNavLink(status);
    },
    error: function(error) {
        console.log('Error:', error);
    }
    });
}

</script>
</body>
</html>

app/views/loans/_form.html.erb
<div class="p-5">
  <%= form_with model: [user, loan], local: true do |f| %>
    <div class="col-md-6 mb-3">
      <%= f.label :amount, class:'form-label'%>
      <%= f.number_field :amount, class:'form-control'%>
      <% if loan.errors[:amount].any? %>
        <div class="error text-danger">amount <%= loan.errors[:amount].first %></div>
      <% end %>
    </div>
    <div class="col-md-6 mb-3">
      <%= f.label 'Interest Rate(%)', class:'form-label' %>
      <%= f.number_field  :interest_rate, step: '0.01',  class:'form-control' %>
      <% if loan.errors[:interest_rate].any? %>
        <div class="error text-danger">Interest Rate <%= loan.errors[:interest_rate].first %></div>
      <% end %>
    </div>
    <% if params[:status].present? %>
    <%= f.hidden_field :status, value: params[:status] %>
    <% end %>
    <div>
      <% if params[:action] == 'adjustment' %>
        <%= f.submit "Update", class:'btn btn-primary' %>
      <% else %>
        <%= f.submit "Create", class:'btn btn-primary' %>
      <% end %>
      <%= link_to "Back", root_path, class: 'btn btn-secondary' %>

    </div>
  <% end %>
</div>

app/views/loans/_list.html.erb
<table class="table">
  <thead class="table-light">
    <tr>
      <th scope="col">Loan ID</th>
      <% if current_user.is_admin? %>
        <th scope="col">User</th>
      <% end %>
      <th scope="col">Status</th>
      <th scope="col">Amount</th>
      <th scope="col">Interest</th>
      <th scope="col" colspan="3" class="text-center">Action</th>
    </tr>
  </thead>
  <tbody>
    <% loans.each do |loan|%>
    <tr>
        <td><%=loan.id %></td>
        <% if current_user.is_admin? %>
          <td scope="col"><%= loan.user.email %></td>
        <% end %>
        <td><span id='loan-status'><%=loan.status.titleize %></span></td>
        <td><%=loan.total_amount%></td>
        <td><%=loan.interest_rate%></td>
        <% if (current_user.is_admin? && loan.status != 'approved') || loan.status == 'open' %>
            <td class="text-center">
                <%= link_to 'view', user_loan_path(current_user.id, loan.id), data: { turbo: false, remote: true }, class:"btn btn-primary btn-sm" %>
            </td>   
        <% end %>
        <% if ['approved', 'waiting_for_adjustment_acceptance'].include?(loan.status) && !current_user.is_admin? %>
            <td><%= button_tag 'Confirm Approval', class:"btn btn-success btn-sm confirm-approval", data_loan_id: loan.id, data_status: loan.status ,onclick:"confirmApproval(this)" %></td>
            <%if loan.status == 'waiting_for_adjustment_acceptance'%>
             <td><%= button_tag "Readjust", id: "my-button", url:'#', type: "button", class: "btn btn-warning btn-sm", data_loan_id: loan.id, onclick: "updateLoan(this)" %></td>
            <% end %>
            <td><%= link_to 'Reject', reject_path(id: loan.id), class:"btn btn-danger btn-sm" %></td>
        <% else %>
            <td colspan="3"></td>
        <% end %>
    </tr>
    <% end %>
    <% if loans.blank? %>
       <tr><td class="text-center border-0 fs-4 fw-bold text-secondary" colspan='8'>No data available.</td></tr> 
    <% end %>
  </tbody>
</table>
    <script>

        function updateLoan(element) {
            var loan_id = element.getAttribute('data_loan_id');
            $.ajax({
                url: '/adjustment',
                method: 'GET',
                data: {id: loan_id, status: 'readjustment'},
                success: function (response) {
                    console.log('Success:', response);
                },
                error: function (error) {
                    console.log('Error:', error);
                }
            });
        }


        function confirmApproval(element){
            var loan_id = element.getAttribute('data_loan_id');
            var loan_status = element.getAttribute('data_status');
            $('.confirm-approval').css('pointer-events', 'none');
            $.ajax({
            url: '/approve',
            method: 'GET',
            data: { loan_id: loan_id, status: loan_status, current_user: '<%= current_user.id %>'},
            success: function(response) {
                $('.confirm-approval').css('pointer-events', '');
            },
            error: function(error) {
                console.log('Error:', error);
            }
            });
        }
    </script>

app/views/loans/adjustment.html.erb
<%= render partial: 'loans/form', locals: {user: @user, loan: @loan} %>

app/views/loans/adjustment.js.erb
$('.content').html("<%= j render partial: 'loans/form', locals: {user: @user, loan: @loan}%>");

app/views/loans/approve.js.erb
console.log(".........approbe js.....")

$('.content').html("<%= j render partial: 'list', locals: {loans: @loans}%>");

app/views/loans/data_list.js.erb
$('.content').html("<%= j render partial: 'list', locals: {loans: @loans}%>");

app/views/loans/index.html.erb
<div id="list-partial">
    <%= render partial: 'list', locals: {loans: @loans}%>
</div>

app/views/loans/new.html.erb
<%= form_with model: [@user, @loan], local: true do |f| %>
<div class="col-md-6 mb-3">
      <%= f.label :amount, class:'form-label'%>
      <%= f.number_field :amount, class:'form-control'%>
      <% if @loan.errors[:amount].any? %>
        <div class="error text-danger">amount <%= @loan.errors[:amount].first %></div>
      <% end %>
</div>
<div class="col-md-6 mb-3">
      <%= f.label 'Interest Rate(%)', class:'form-label' %>
      <%= f.number_field  :interest_rate, step: '0.01',  class:'form-control' %>
      <% if @loan.errors[:interest_rate].any? %>
        <div class="error text-danger">Interest Rate <%= @loan.errors[:interest_rate].first %></div>
      <% end %>
</div>
<div>
      <%= f.submit "Create", class:'btn btn-primary' %>
      <%= link_to "Back", root_path, class: 'btn btn-secondary' %>

</div>
<% end %>

app/views/loans/new.js.erb
$('.content').html("<%= j render partial: 'loans/form', locals: {user: @user, loan: @loan}%>");

app/views/loans/reject.js.erb
$('.content').html("<%= j render partial: 'list', locals: {loans: @loans}%>");

app/views/loans/repay_loan.js.erb
$('.content').html("<%= j render partial: 'list', locals: {loans: @loans}%>");

app/views/loans/show.html.erb
<div class="container mt-4">
  <!-- Title and Loan Details -->
  <div class="row">
    <div class="col-md-12 text-center">
      <h1 class="display-4 mb-4"><%= @loan.status.titleize %></h1>
      <h2 class="mb-3">Total Amount: <%= (@loan.total_amount) %> Rs</h2>
      <h3 class="mb-3">Amount<span class="fs-6">(principle)</span>: <%= (@loan.amount) %> Rs</h3>
      <p class="lead">Interest Rate (%): <%= @loan.interest_rate %></p>
    </div>
  </div>

  <!-- Action Buttons -->
  <% if ['requested', 'readjustment'].include?(@loan.status) %>
    <div class="row mb-4">
      <div class="col-md-12 text-center">
        <%= button_tag "Reject Loan", id: "my-button", class: "btn btn-secondary me-2", onclick: "reject_request()" %>
        <%= button_tag "Adjust Loan", id: "my-button", url:'#', type: "button", class: "btn btn-warning me-2", onclick: "updateLoan()" %>
        <%= link_to "Approve Loan", approve_path(id: @loan.id, user_id: @loan.user_id), class: "btn btn-success" + (current_user.amount >= @loan.amount ? '' : ' disabled') %>
      </div>
    </div>
  <% end %>

  <!-- Repay Loan Button -->
  <% if @loan.status == 'open' && !current_user.is_admin? %>
    <div class="row mb-4">
      <div class="col-md-12 text-center">
        <%= link_to 'Repay Loan', repay_loan_path(id: @loan.id), class: "btn btn-success" %>
        <%#= button_tag "Repay Loan", class: "btn btn-success repay-loan", onclick: "repayLoan()" %>
      </div>
    </div>
  <% end %>

  <!-- Adjustments List -->
  <% if @loan.adjustments.present? %>
    <div class="row">
      <div class="col-md-12">
        <h2 class="mb-3">Adjustments</h2>
        <ul class="list-group">
          <% @loan.adjustments.order(:created_at).each do |adjustment| %>
            <li>Status: <%= adjustment.status.titleize %> | Interest Rate: <%= adjustment.interest_rate %> | Amount: <%= adjustment.amount %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <!-- Back Link -->
  <div class="row mt-4">
    <div class="col-md-12 text-center">
      <%= link_to "Back", '#', onclick: 'history.back(); return false;', class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

<script>
    function updateLoan() {
        $.ajax({
            url: '/adjustment',
            method: 'GET',
            data: {id: <%= @loan.id %>},
            success: function (response) {
                console.log('Success:', response);
            },
            error: function (error) {
                console.log('Error:', error);
            }
        });
    }

<!--    function repayLoan() {-->
<!--        $('.repay-loan').css('pointer-events', 'none');-->

<!--        $.ajax({-->
<!--            url: '/repay_loan',-->
<!--            method: 'GET',-->
<!--            data: {id: <#%= @loan.id %>},-->
<!--            success: function (response) {-->
<!--                $('.repay-loan').css('pointer-events', '');-->
<!--                console.log('Success:', response);-->
<!--            },-->
<!--            error: function (error) {-->
<!--                console.log('Error:', error);-->
<!--            }-->
<!--        });-->
<!--    }-->

    function reject_request() {
        $.ajax({
            url: '/reject',
            method: 'GET',
            data: {id: <%= @loan.id %>},
            success: function (response) {
                console.log('Success:', response);
            },
            error: function (error) {
                console.log('Error:', error);
            }
        });
    }

    function adjustment() {
        $.ajax({
            url: '/adjustment',
            method: 'GET',
            data: {id: <%= @loan.id %>},
            success: function (response) {
                console.log('Success:', response);
            },
            error: function (error) {
                console.log('Error:', error);
            }
        });
    }

</script>